# Generated by Django 4.2.25 on 2025-10-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm_polls', '0005_choice_votes_count_alter_vote_choice_alter_vote_poll_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'permissions': [('can_suspend_poll', 'Can suspend poll')]},
        ),
        migrations.AddField(
            model_name='poll',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
