# Generated by Django 4.2.25 on 2025-10-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comm_polls', '0007_managerrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={},
        ),
        migrations.RemoveField(
            model_name='poll',
            name='is_suspended',
        ),
    ]
