# Generated by Django 4.2.25 on 2025-10-22 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comm_polls', '0008_alter_poll_options_remove_poll_is_suspended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='details',
        ),
    ]
