name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run migrations
        run: python manage.py migrate

      - name: Run unit tests
        run: python manage.py test comm_polls

      - name: Run integration tests
        run: python manage.py test comm_polls.integration_tests

      - name: Run E2E tests
        env:
          DISPLAY: :99  # headless mode
        run: python manage.py test comm_polls.e2e_tests

      - name: Run coverage report
        run: |
          coverage run --source='.' manage.py test
          coverage report
          coverage xml
